version: "3.7"

services:
  shlink:
    hostname: shlink
    image: sharp6292/shlink:latest

    environment:
      SHORT_DOMAIN_HOST: ${DOMAIN:?err}
      SHORT_DOMAIN_SCHEMA: https
      GEOLITE_LICENSE_KEY: ${GEOLITE_LICENSE_KEY:?err}
      DB_DRIVER: postgres
      DB_USER: postgres
      DB_PASSWORD: ${POSTPASS:?err}
      DB_HOST: postgres
      SHARPDOMAIN: ${DOMAIN:?err}

    restart: always

volumes:
  shlink:

networks:
    default:
        external:
            name: sharpnet
