version: "3.7"

services:
  shlink:
    hostname: shlink
    image: sharp6292/shlink:latest

    environment:
      SHORT_DOMAIN_HOST: l.mcaq.me
      SHORT_DOMAIN_SCHEMA: https
      GEOLITE_LICENSE_KEY: ${GEOLITE_LICENSE_KEY}
      DB_DRIVER: postgres
      DB_USER: postgres
      DB_PASSWORD: ${POSTPASS}
      DB_HOST: postgres

    restart: always

volumes:
  shlink:

networks:
    default:
        external:
            name: sharpnet
